class_name DungeonManager
extends Node2D


##This class should know how the rooms are arranged and in which room the player currently is. 

@onready var dungeonrooms: Node2D = $Dungeonrooms
@onready var test_player: Player = $"../TestPlayer"
#for prototype to show what happened: example tried walking through door with no corresponding entrance
@onready var info: Panel = $Info
@onready var label: Label = $Info/Label


var templateRoom = preload("res://Scenes/DungeonThings/dungeon_room.tscn")

var allDungeonScenes: Dictionary[Vector2i, Node] = {}

var posOfPlayer: Vector2i
var playerTransformation: Transform2D

const playerPosNorth: Vector2 = Vector2(144, 48)
const playerPosSouth: Vector2 = Vector2(144, 240)
const playerPosWest: Vector2 = Vector2(48, 144)
const playerPosEast: Vector2 = Vector2(240, 144)


# input could be the dictionary generated by build_dungeon_screen
# so here would be generated a seperate dictionary with the vector2 and the instanciated Scene
# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	playerTransformation = test_player.transform
	playerTransformation.origin = Vector2(126,126)
	GlobalEventBus.subscribe(self)
	pass # Replace with function body.


# Called every frame. '_delta' is the elapsed time since the previous frame.
func _process(_delta: float) -> void:
	pass


#func transformDictionaryIntoScenes(dictionary: Dictionary):
	#print("got the signal")
	#pass


func _on_build_dungeon_screen_export_all_rooms(dict: Dictionary, startRoom: Vector2i) -> void:
	print("got the signal")
	posOfPlayer = startRoom
	#here i would have to loop through the key value pairs and generate the scenes
	for key in dict.keys():
		var tileData = dict.get(key).tileData
		if (tileData != null):
			var newRoom = templateRoom.instantiate()
			newRoom.setTileData(tileData)
			dungeonrooms.add_child(newRoom)
			allDungeonScenes.set(key, newRoom)
		else:
			allDungeonScenes.set(key, null)
	print("got them all I guess")
	startInBeginningRoom(startRoom)
	pass # Replace with function body.


func movePlayerToNextRoom(directio: Enums.DIRECTION) -> void:
	print("move player to ", directio)
	var movement: Vector2i
	var playerPosInDungeon: Vector2i
	match directio:
		Enums.DIRECTION.NORTH:
			playerPosInDungeon = playerPosSouth
			movement= Vector2i(0,-1)
		Enums.DIRECTION.SOUTH:
			playerPosInDungeon = playerPosNorth
			movement = Vector2i(0,1)
		Enums.DIRECTION.WEST:
			playerPosInDungeon = playerPosEast
			movement = Vector2i(-1, 0)
		Enums.DIRECTION.EAST:
			playerPosInDungeon = playerPosWest
			movement = Vector2i(1,0)
	var futureRoom = posOfPlayer + movement
	if (allDungeonScenes.get(futureRoom) != null):
		var testing = testIfRoomsConnect(posOfPlayer, futureRoom)
		if(testing):
			allDungeonScenes.get(posOfPlayer).makeUnplayable()
			test_player.position = playerPosInDungeon
			posOfPlayer += movement
			allDungeonScenes.get(posOfPlayer).makePlayable()
		else: 
			blendOutInfo("there is a wall on the other side")
		pass
	else:
		fallIntoVoid()
		
	#new Room from dictionary
	#disable old rooma
	#move player into fitting position in new room
	pass

func testIfRoomsConnect(start: Vector2i, dest: Vector2i) -> bool:
	var beginRoom: Tile_Data = allDungeonScenes.get(start).tileData
	var destRoom: Tile_Data = allDungeonScenes.get(dest).tileData
	var direction: Vector2i = start - dest
	match direction:
		Vector2i(0,-1):
			return beginRoom.isSouth() and destRoom.isNorth()
		Vector2i(0,1):
			return beginRoom.isNorth() and destRoom.isSouth()
		Vector2i(-1,0):
			return beginRoom.isEast() and destRoom.isWest()
		Vector2i(1,0):
			return beginRoom.isWest() and destRoom.isEast()			
	return false


func startInBeginningRoom(startRoom: Vector2i) -> void:
	var room = allDungeonScenes.get(startRoom)
	room.makePlayable()
	test_player.visible = true
	test_player.position = playerPosNorth


func blendOutInfo(message: String) -> void:
	label.text = message
	info.visible = true
	var fadeOutTween = create_tween()
	fadeOutTween.tween_property(info, "modulate", Color(0.0, 0.0, 0.0, 0.0), 1)
	fadeOutTween.tween_callback(restoreInfo)


func restoreInfo() -> void:
	info.visible = false
	info.modulate = Color(1.0, 1.0, 1.0, 1.0)


func fallIntoVoid() -> void:
	allDungeonScenes.get(posOfPlayer).makeUnplayable()
	var rotatePlayerAndShrinkPlayer = create_tween()
	rotatePlayerAndShrinkPlayer.tween_property(test_player, "transform", Transform2D(test_player.rotation + PI, Vector2(0.001,0.001),playerTransformation.get_skew(), playerTransformation.get_origin()), 0.3 )
	rotatePlayerAndShrinkPlayer.tween_callback(finishedVoid)
	pass


func finishedVoid(): 
	print("player fell into void")
	test_player.transform = playerTransformation
	blendOutInfo("you fell into the void")
	allDungeonScenes.get(posOfPlayer).makePlayable()
