class_name DungeonManager
extends Node2D


##This class should know how the rooms are arranged and in which room the player currently is. 

@onready var dungeonrooms: Node2D = $Dungeonrooms

var templateRoom = preload("res://Scenes/dungeon_room.tscn")

var allDungeonScenes: Dictionary = {}


# input could be the dictionary generated by build_dungeon_screen
# so here would be generated a seperate dictionary with the vector2 and the instanciated Scene
# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass


#func transformDictionaryIntoScenes(dictionary: Dictionary):
	#print("got the signal")
	#pass


func _on_build_dungeon_screen_export_all_rooms(dict: Dictionary) -> void:
	print("got the signal")
	#here i would have to loop through the key value pairs and generate the scenes
	for key in dict.keys():
		var tileData = dict.get(key)
		if (tileData != null):
			var newRoom = templateRoom.instantiate()
			newRoom.setTileData(tileData)
			dungeonrooms.add_child(newRoom)
			allDungeonScenes.set(key, newRoom)
		else:
			allDungeonScenes.set(key, null)
	print("got them all I guess")
	pass # Replace with function body.
