class_name DungeonManager
extends Node2D


##This class should know how the rooms are arranged and in which room the player currently is. 

# input could be the dictionary generated by build_dungeon_screen
# so here would be generated a seperate dictionary with the vector2 and the instanciated Scene
# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass


#func transformDictionaryIntoScenes(dictionary: Dictionary):
	#print("got the signal")
	#pass


func _on_build_dungeon_screen_export_all_rooms(dict: Dictionary) -> void:
	print("got the signal")
	#here i would have to loop through the key value pairs and generate the scenes
	
	pass # Replace with function body.
