class_name DungeonManager
extends Node2D


##This class should know how the rooms are arranged and in which room the player currently is. 

@onready var dungeonrooms: Node2D = $Dungeonrooms
@onready var test_player: Player = $"../TestPlayer"

var templateRoom = preload("res://Scenes/dungeon_room.tscn")

var allDungeonScenes: Dictionary = {}

var posOfPlayer: Vector2 = Vector2(0,0)


const playerPosNorth: Vector2 = Vector2(144, 48)
const playerPosSouth: Vector2 = Vector2(144, 240)
const playerPosWest: Vector2 = Vector2(48, 144)
const playerPosEast: Vector2 = Vector2(240, 144)


# input could be the dictionary generated by build_dungeon_screen
# so here would be generated a seperate dictionary with the vector2 and the instanciated Scene
# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	GlobalEventBus.subscribe(self)
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass


#func transformDictionaryIntoScenes(dictionary: Dictionary):
	#print("got the signal")
	#pass


func _on_build_dungeon_screen_export_all_rooms(dict: Dictionary) -> void:
	print("got the signal")
	#here i would have to loop through the key value pairs and generate the scenes
	for key in dict.keys():
		var tileData = dict.get(key)
		if (tileData != null):
			var newRoom = templateRoom.instantiate()
			newRoom.setTileData(tileData)
			dungeonrooms.add_child(newRoom)
			allDungeonScenes.set(key, newRoom)
		else:
			allDungeonScenes.set(key, null)
	print("got them all I guess")
	startInBeginningRoom()
	pass # Replace with function body.


func movePlayerToNextRoom(directio: Enums.DIRECTION) -> void:
	print("move player to ", directio)
	allDungeonScenes.get(posOfPlayer).makeUnplayable()
	var movement: Vector2
	match directio:
		Enums.DIRECTION.NORTH:
			test_player.position = playerPosSouth
			movement= Vector2(-1,-0)
		Enums.DIRECTION.SOUTH:
			test_player.position = playerPosNorth
			movement = Vector2(1,0)
		Enums.DIRECTION.WEST:
			test_player.position = playerPosEast
			movement = Vector2(0, -1)
		Enums.DIRECTION.EAST:
			test_player.position = playerPosWest
			movement = Vector2(0,1)
	posOfPlayer += movement
	allDungeonScenes.get(posOfPlayer).makePlayable()
	#new Room from dictionary
	#disable old rooma
	#move player into fitting position in new room
	pass


func startInBeginningRoom() -> void:
	var room = allDungeonScenes.get(Vector2(0,0))
	room.makePlayable()
	test_player.visible = true
	test_player.position = playerPosNorth
